### PR TITLE
Update text files from github/linguist

### PR DESCRIPTION
**Pull request by Yash-Singh1**

### CODE REVIEW

**Comment by sindresorhus** [comment]
What exactly is the source?

**Comment by Yash-Singh1** [comment]
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by sindresorhus** [comment]
The problem with just blindly including everything from that list is that it contains a lot of obsolete/ancient stuff that is not relevant to detection here and could conflict with a newer extension of the same name. I'm not going to merge this, but if you want to manually cherry-pick some extensions from that list for popular and modern languages, I'm happy to merge that.

**Comment by sindresorhus** [comment]
For example, extensions like https://github.com/sindresorhus/text-extensions/pull/25/files#diff-64d191a6e7f75688508e628e81b1d1a26e2dded4779b3e745e6ede0b9a7e7b41R1077 totally makes sense to add.

And https://github.com/sindresorhus/text-extensions/pull/25/files#diff-64d191a6e7f75688508e628e81b1d1a26e2dded4779b3e745e6ede0b9a7e7b41R1123

**Pull request closed without merging**
